### ISSUE TITLE
Mobile user agent ignored

### ISSUE THREAD

**Issue by jack-mil** [jack-mil/bing-rewards#30]
For me it still does not work on either Chrome or Brave (Edge seems to ignore completely mobile user agent). Tried to change user agents, still no luck
I even ran:
```
taskkill /f /im "chrome.exe"
taskkill /f /im "brave.exe"
```
before the script. Browser opens, does searches in mobile view, but I still see 0/60 mobile searches.
Maybe agents need to be updated? This is my config:
```
{
    "desktop-count": 34,
    "mobile-count": 40,
    "load-delay": 1.5,
    "search-delay": 2,
    "search-url": "https://www.bing.com/search?q=",
    "desktop-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36 Edg/83.0.478.37",
    "mobile-agent": "Mozilla/5.0 (Windows Phone 10.0; Android 6.0.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Mobile Safari/537.36 Edge/18.19041",
    "browser-path": "C:\\Users\\G\\AppData\\Local\\BraveSoftware\\Brave-Browser\\Application\\brave.exe"
}
```

_Originally posted by @N190392 in https://github.com/jack-mil/bing-rewards/issues/13#issuecomment-1525170102_

**Comment by jack-mil** [comment]
@N190392 I am bringing this issue into it's own thread so the other does not get polluted.
Can you give me some more information about your setup? What operating system and browser versions are you working with? Are the desktop rewards being counted? Anything else unusual about your setup?

**Comment by N190392** [comment]
- I use Win10 x64. Python 10.10.
- Mobile stopped working about a week ago.
- I use Chrome for this, Brave installed for testing purposes because it stopped working.
Brave atm is 112.1.5.121 and Chrome 112.0.5615.138. Both installed using WINGET.
- When it worked, I had changed Mobile agent to latest Edge on iOS 16, but now it doesn't work any.
It detects it, because browser starts Bing in mobile mode, but no rewards.
- Web and Desktop rewards seem to working fine. Though default 34 desktop limit must be increased to get 90/90.

**Comment by N190392** [comment]
Okay, so Chrome etc does not work even when lanually launching --user-agent argument. May it be because Chromium is phasing out User Agents instead of Client Hints? https://developer.chrome.com/articles/user-agent-client-hints/

So I did a manual test with Firefox:
1. about:config
2. type: **general.useragent.override;** select: **string**; **+**
3. Mobile gets counted.

Question for @jack-mil 
For this to work with firefox, app would need to get updated. As Firefox does not support User Agent string, the profiles must be specified. So programs should be launched like this.
`C:\Program Files\WindowsApps\Mozilla.Firefox_112.0.2.0_x64__n80bbvh6b1yt2\VFS\ProgramFiles\Firefox Package Root\firefox.exe -p "default"`
`C:\Program Files\WindowsApps\Mozilla.Firefox_112.0.2.0_x64__n80bbvh6b1yt2\VFS\ProgramFiles\Firefox Package Root\firefox.exe -p "mobile"`

So it requires some setting up. Like making "Mobile" profile
1. about:profiles
2. Create a New Profile
3. Doing the steps mentioned above for the new profile.

That means that the config file should get 2 new variables (default profile name, extra mobile profile name).

**Comment by jack-mil** [comment]
I would like to support Firefox as I use that mainly, I couldn't originally because as you mentioned, there is no command line argument for setting the user agent string.

Oddly, I am using the same version of Chrome as you, and I was able to receive mobile award points. Maybe it's an issue on the Bing/ MS account side?

( `bing-rewards --mobile --count 1`)
![image](https://user-images.githubusercontent.com/62065280/235517128-e5a20956-4839-4a1a-96ef-301f4103e3dd.png)

**Comment by N190392** [comment]
During testing I also had that suspicion that problem lies on Microsoft's end. Everything worked until it just... stopped without any changes and with mobile UA. And none of the Chromium browsers does the trick, only Firefox.
For example, even Bing is different (instead of 150/100/20 like in your screenshot, I have 90/12/60 points available).

**Comment by jack-mil** [comment]
That is very curious. I have noticed the "rewards level" influences the daily quota. That screenshot is level 2

**Comment by N190392** [comment]
![IMG_8646](https://user-images.githubusercontent.com/57212053/235532903-e7c5219a-f2d5-4f4f-9400-7f9ba9569e31.jpeg)
It must be region dependent.

**Comment by jack-mil** [comment]
Interesting observation. You can use the --nowindow and --noexit args to go along with this. 
Strange how Edge is acting

**Comment by gdwnldsKSC** [comment]
Chrome 114.0.5735.110 here, not counting any mobile points it seems.

**Comment by jack-mil** [comment]
Closing this for now, but pinning for future reference if anomalies keep cropping up.

**Comment by jack-mil** [comment]
Closing this for now, but pinning for future reference if anomalies keep cropping up.
